
GET http://localhost:3000/message

###
POST http://localhost:3000/post

###
GET http://localhost:3000/post

###
DELETE http://localhost:3000/post/647f1b36641c56d1ac97a843

###
PUT http://localhost:3000/post/647f1b36641c56d1ac97a843